/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KernelRouteImport } from './routes/kernel'
import { Route as VoidRouteImport } from './routes/void'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelRoute = KernelRouteImport.update({
  id: '/kernel',
  path: '/kernel',
  getParentRoute: () => rootRouteImport,
} as any)
const VoidRoute = VoidRouteImport.update({
  id: '/void',
  path: '/void',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kernel': typeof KernelRoute
  '/void': typeof VoidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kernel': typeof KernelRoute
  '/void': typeof VoidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kernel': typeof KernelRoute
  '/void': typeof VoidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kernel' | '/void'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kernel' | '/void'
  id: '__root__' | '/' | '/kernel' | '/void'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KernelRoute: typeof KernelRoute
  VoidRoute: typeof VoidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernel': {
      id: '/kernel'
      path: '/kernel'
      fullPath: '/kernel'
      preLoaderRoute: typeof KernelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/void': {
      id: '/void'
      path: '/void'
      fullPath: '/void'
      preLoaderRoute: typeof VoidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KernelRoute: KernelRoute,
  VoidRoute: VoidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
