/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadiaRouteImport } from './routes/arcadia'
import { Route as FolioRouteImport } from './routes/folio'
import { Route as GridlineRouteImport } from './routes/gridline'
import { Route as KernelRouteImport } from './routes/kernel'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VoidRouteImport } from './routes/void'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadiaRoute = ArcadiaRouteImport.update({
  id: '/arcadia',
  path: '/arcadia',
  getParentRoute: () => rootRouteImport,
} as any)
const FolioRoute = FolioRouteImport.update({
  id: '/folio',
  path: '/folio',
  getParentRoute: () => rootRouteImport,
} as any)
const GridlineRoute = GridlineRouteImport.update({
  id: '/gridline',
  path: '/gridline',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelRoute = KernelRouteImport.update({
  id: '/kernel',
  path: '/kernel',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VoidRoute = VoidRouteImport.update({
  id: '/void',
  path: '/void',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcadia': typeof ArcadiaRoute
  '/folio': typeof FolioRoute
  '/gridline': typeof GridlineRoute
  '/kernel': typeof KernelRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/void': typeof VoidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcadia': typeof ArcadiaRoute
  '/folio': typeof FolioRoute
  '/gridline': typeof GridlineRoute
  '/kernel': typeof KernelRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/void': typeof VoidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcadia': typeof ArcadiaRoute
  '/folio': typeof FolioRoute
  '/gridline': typeof GridlineRoute
  '/kernel': typeof KernelRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/void': typeof VoidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcadia'
    | '/folio'
    | '/gridline'
    | '/kernel'
    | '/studio'
    | '/tools'
    | '/void'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcadia'
    | '/folio'
    | '/gridline'
    | '/kernel'
    | '/studio'
    | '/tools'
    | '/void'
  id:
    | '__root__'
    | '/'
    | '/arcadia'
    | '/folio'
    | '/gridline'
    | '/kernel'
    | '/studio'
    | '/tools'
    | '/void'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadiaRoute: typeof ArcadiaRoute
  FolioRoute: typeof FolioRoute
  GridlineRoute: typeof GridlineRoute
  KernelRoute: typeof KernelRoute
  StudioRoute: typeof StudioRoute
  ToolsRoute: typeof ToolsRoute
  VoidRoute: typeof VoidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcadia': {
      id: '/arcadia'
      path: '/arcadia'
      fullPath: '/arcadia'
      preLoaderRoute: typeof ArcadiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folio': {
      id: '/folio'
      path: '/folio'
      fullPath: '/folio'
      preLoaderRoute: typeof FolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gridline': {
      id: '/gridline'
      path: '/gridline'
      fullPath: '/gridline'
      preLoaderRoute: typeof GridlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernel': {
      id: '/kernel'
      path: '/kernel'
      fullPath: '/kernel'
      preLoaderRoute: typeof KernelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/void': {
      id: '/void'
      path: '/void'
      fullPath: '/void'
      preLoaderRoute: typeof VoidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadiaRoute: ArcadiaRoute,
  FolioRoute: FolioRoute,
  GridlineRoute: GridlineRoute,
  KernelRoute: KernelRoute,
  StudioRoute: StudioRoute,
  ToolsRoute: ToolsRoute,
  VoidRoute: VoidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
